/* Generated by Together */

#ifndef _VCF_COMEXCEPTION_H__
#define _VCF_COMEXCEPTION_H__
#include "vcf/FoundationKit/BasicException.h"
class COMException : public VCF::BasicException {
};
#endif // _VCF_COMEXCEPTION_H__


