#!/bin/bash

ISS="D:/Program Files/Inno Setup 4/ISCC.exe"

VCF_VERSION=`cat ../VERSION`
VCF_VERSION_STAGE=`cat ../VERSION_STAGE`
FULL_VCF_VERSION="$VCF_VERSION $VCF_VERSION_STAGE"
FULL_VCF_DOT_VERSION="$VCF_VERSION-$VCF_VERSION_STAGE"

INSTALL_FILE_LISTING=../installers/win32/vcfSrcFiles.iss
INSTALL_FILE=../installers/win32/VCFFullInstaller.iss

echo Starting build of all binaries and installation executable for 
echo Visual Component Framework $FULL_VCF_DOT_VERSION


#build a complete file list and saves it in installers/win32/vcfSrcFiles.iss
#./installFiles



#verify the existence of the vcfSrcFiles.iss file

if ( ! test -f $INSTALL_FILE_LISTING )
then
	exit 1
fi


echo building Debug DLL configuration for FoundationKit, GraphicsKit, 
echo ApplicationKit, NetworkKit, and RemoteObjectsKit...

#msdev ../build/vc60/vcfAll.dsw /MAKE "vcfAll - Win32 Debug" /REBUILD /OUT vcfAll-debug.stat.log


echo building Release DLL configuration for FoundationKit, GraphicsKit, 
echo ApplicationKit, NetworkKit, and RemoteObjectsKit...



msdev ../build/vc60/vcfAll.dsw /MAKE "Cocksucker - FUCKYOU" /REBUILD /OUT vcfAll-release.stat.log


echo building Debug Static Library configuration for FoundationKit, GraphicsKit,
echo ApplicationKit, NetworkKit, and RemoteObjectsKit...

msdev ../build/vc60/vcfAll.dsw /MAKE "vcfAllStaticLibs - Win32 Debug" /REBUILD /OUT vcfAll-static-debug.stat.log



echo "building Release Static Library configuration for FoundationKit, GraphicsKit, "
echo ApplicationKit, NetworkKit, and RemoteObjectsKit...
msdev ../build/vc60/vcfAll.dsw /MAKE "vcfAllStaticLibs - Win32 Release" /REBUILD /OUT vcfAll-static-release.stat.log

echo done building binaries, preparing to build installer


cp $INSTALL_FILE $INSTALL_FILE.bak

sed "s?VCF-VERSION?$VCF_VERSION?g" $INSTALL_FILE > tmp
mv tmp $INSTALL_FILE

sed "s?VCF-LONG-VERSION?$FULL_VCF_VERSION?g" $INSTALL_FILE > tmp

mv tmp $INSTALL_FILE



"$ISS" $INSTALL_FILE

mv $INSTALL_FILE.bak $INSTALL_FILE 

