#ifndef _VCF_TYPECASTEXCEPTION_H__
#define _VCF_TYPECASTEXCEPTION_H__
//TypeCastException.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */

#include "vcf/FoundationKit/FrameworkConfig.h"
#include "vcf/FoundationKit/BasicException.h"
#include "vcf/FoundationKit/ErrorStrings.h"

namespace VCF
{
/**
\class TypeCastException TypeCastException.h "vcf/FoundationKit/TypeCastException.h"
*/
class FOUNDATIONKIT_API TypeCastException : public BasicException {
public:
	TypeCastException(const String & message ):
		BasicException( message ){

	};

	TypeCastException():
		BasicException( INVALID_POINTER_ERROR ){

	};

	TypeCastException( const String & message, const int lineNumber ):
		BasicException(message, lineNumber){};

	virtual ~TypeCastException() throw() {};

};

};


#endif // _VCF_TYPECASTEXCEPTION_H__

/**
$Id$
*/
