/* Generated by Together */

#ifndef _VCF_NOIMPLEMENTERFOUNDEXCEPTION_H__
#define _VCF_NOIMPLEMENTERFOUNDEXCEPTION_H__
#include "vcf/FoundationKit/BasicException.h"

class NoImplementerFoundException : public VCF::BasicException {

};
#endif // _VCF_NOIMPLEMENTERFOUNDEXCEPTION_H__


