#ifndef _VCF_THREADEXCEPTION_H__
#define _VCF_THREADEXCEPTION_H__
//ThreadException.h

/*
Copyright 2000-2004 The VCF Project.
Please see License.txt in the top level directory
where you installed the VCF.
*/


#if _MSC_VER > 1000
#   pragma once
#endif


/* Generated by Together */


#include "vcf/FoundationKit/BasicException.h"

class FRAMEWORK_API ThreadException : public VCF::BasicException {

};


/**
*CVS Log info
*$Log$
*Revision 1.1.2.2  2004/04/29 04:07:13  marcelloptr
*reformatting of source files: macros and csvlog and copyright sections
*
*/


#endif // _VCF_THREADEXCEPTION_H__


